"""Render publication-ready figures + a markdown report from any panel.

Panel-agnostic: point it at the synthetic panel today or the real panel later
and nothing changes. A banner is derived from the panel's ``confidence`` column
so a figure built on synthetic or provisional data is unmistakably labelled.

Run:
    uv run python sections/engineering-workforce/pipeline/report.py                 # synthetic
    uv run python .../report.py --panel data/processed/panel.parquet --outdir ...   # real
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd

sys.path.insert(0, str(Path(__file__).parent))
import analysis  # noqa: E402

from quasioptimal.data import load_processed  # noqa: E402
from quasioptimal.paths import processed_dir, section_dir  # noqa: E402
from quasioptimal.viz import set_style  # noqa: E402

DEFAULT_OUTDIR = section_dir("engineering-workforce") / "outputs"


def data_banner(panel: pd.DataFrame) -> str | None:
    conf = set(panel.get("confidence", pd.Series(dtype=str)).dropna().unique())
    if "synthetic" in conf:
        return "SYNTHETIC DATA — illustrative only, not a result"
    if "literature_unverified" in conf:
        return "PROVISIONAL — unverified literature anchors, not a result"
    if conf <= {"primary", "secondary"} and conf:
        return None
    return "MIXED provenance — check confidence per series"


def _watermark(fig, banner: str | None) -> None:
    if banner:
        fig.text(
            0.5,
            0.5,
            banner.split(" — ")[0],
            fontsize=42,
            color="red",
            alpha=0.10,
            ha="center",
            va="center",
            rotation=25,
            zorder=0,
        )
        fig.text(0.01, 0.005, banner, fontsize=8, style="italic", color="red", alpha=0.8)


def fig_longrun(panel: pd.DataFrame, definition: str, outdir: Path, banner) -> Path:
    set_style()
    fig, ax = plt.subplots()
    for entity, g in panel[panel["definition"] == definition].groupby("entity"):
        g = g.dropna(subset=["share_per_100k"]).sort_values("year")
        if len(g):
            ax.plot(g["year"], g["share_per_100k"], label=entity, lw=1.6)
    ax.set_yscale("log")
    ax.set_title(f"Engineers per 100,000 population — {definition} definition")
    ax.set_xlabel("Year")
    ax.set_ylabel("Engineers per 100k (log)")
    ax.legend(fontsize=8, ncol=2)
    _watermark(fig, banner)
    out = outdir / f"longrun_{definition}.png"
    fig.savefig(out)
    plt.close(fig)
    return out


def fig_breaks_focus(
    panel: pd.DataFrame, entity: str, definition: str, outdir: Path, banner
) -> Path:
    set_style()
    s = analysis.series(panel, entity, definition)
    model = analysis.detect_changepoints(s)
    regimes = analysis.fit_regimes(s, model.break_years)
    fig, ax = plt.subplots()
    ax.plot(s["year"], s["share_per_100k"], lw=1.8, color="C0")
    ax.set_yscale("log")
    for by in model.break_years:
        ax.axvline(by, color="C3", ls="--", lw=1, alpha=0.7)
        ax.text(by, ax.get_ylim()[1], f" break {by}", color="C3", fontsize=8, va="top")
    for r in regimes:
        mid = (r.year_from + r.year_to) / 2
        ax.text(
            mid,
            r.end_share,
            f"{r.annual_growth * 100:.1f}%/yr",
            fontsize=8,
            ha="center",
            va="bottom",
            color="C0",
        )
    ax.set_title(f"{entity} ({definition}) — detected regimes")
    ax.set_xlabel("Year")
    ax.set_ylabel("Engineers per 100k (log)")
    _watermark(fig, banner)
    out = outdir / f"regimes_{entity.replace(' ', '')}_{definition}.png"
    fig.savefig(out)
    plt.close(fig)
    return out


def fig_snapshot(panel: pd.DataFrame, year: int, definition: str, outdir: Path, banner) -> Path:
    set_style()
    snap = analysis.cross_country_snapshot(panel, year, definition)
    fig, ax = plt.subplots()
    ax.barh(snap["entity"], snap["share_per_100k"], color="C0")
    ax.invert_yaxis()
    ax.set_title(f"Engineer share by country, ~{year} ({definition})")
    ax.set_xlabel("Engineers per 100k")
    _watermark(fig, banner)
    out = outdir / f"snapshot_{year}_{definition}.png"
    fig.savefig(out)
    plt.close(fig)
    return out


def write_report(panel: pd.DataFrame, figs: list[Path], outdir: Path, banner) -> Path:
    growth = analysis.growth_table(panel)
    lines = ["# Engineering workforce — analysis report", ""]
    if banner:
        lines += [f"> **{banner}.** Regenerate on real data with the same commands.", ""]
    lines += [
        "Generated by `pipeline/report.py` from the panel "
        f"(`{len(panel)}` rows, entities: {', '.join(sorted(panel['entity'].unique()))}).",
        "",
        "## Detected structural breaks & growth regimes",
        "",
        "Breaks are dated by piecewise-log-linear changepoint detection "
        "(`analysis.detect_changepoints`, model order by BIC); growth is the "
        "annualised rate of the engineer share within each regime.",
        "",
    ]
    if len(growth):
        show = growth.copy()
        show["annual_growth_pct"] = show["annual_growth_pct"].round(2)
        show["start_share"] = show["start_share"].round(2)
        show["end_share"] = show["end_share"].round(1)
        lines.append(show.to_markdown(index=False))
    lines += ["", "## Cross-country snapshots", ""]
    for year in (1900, 2020):
        snap = analysis.cross_country_snapshot(panel, year, "contemporary")
        if len(snap):
            snap = snap.assign(share_per_100k=snap["share_per_100k"].round(2))
            lines += [f"### ~{year} (contemporary)", "", snap.to_markdown(index=False), ""]
    lines += ["## Figures", ""]
    for f in figs:
        lines.append(f"![{f.stem}]({f.relative_to(outdir.parent)})")
    report = outdir / "report.md"
    report.write_text("\n".join(lines) + "\n")
    return report


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--panel", default=str(processed_dir("engineering-workforce") / "panel_synth.parquet")
    )
    ap.add_argument("--outdir", default=str(DEFAULT_OUTDIR))
    args = ap.parse_args()

    panel = load_processed(Path(args.panel))
    outdir = Path(args.outdir)
    (outdir / "figures").mkdir(parents=True, exist_ok=True)
    fdir = outdir / "figures"
    banner = data_banner(panel)

    figs = [
        fig_longrun(panel, "contemporary", fdir, banner),
        fig_longrun(panel, "modern", fdir, banner),
        fig_breaks_focus(panel, "United States", "contemporary", fdir, banner),
        fig_snapshot(panel, 1900, "contemporary", fdir, banner),
        fig_snapshot(panel, 2020, "contemporary", fdir, banner),
    ]
    report = write_report(panel, figs, outdir, banner)
    print(f"Banner: {banner}")
    print(f"Wrote {report} and {len(figs)} figures under {fdir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
